export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_CURRENT = "UPDATE_CURRENT";
export const FILTER_CONTACTS = "REMOVE_ALERT";
export const CLEAR_FILTER = "CLEAR_FILTER";