export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const FILTER_CONTACTS = "REMOVE_ALERT";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_LOADING = "SET_LOADING";
// AuthTypes
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// AlertTypes
export const SET_LOGIN_ALERT = "SET_LOGIN_ALERT";
export const SET_REGISTER_ALERT = "SET_REGISTER_ALERT";
export const REMOVE_LOGIN_ALERT = "REMOVE_LOGIN_ALERT";
export const REMOVE_REGISTER_ALERT = "REMOVE_REGISTER_ALERT";
export const CLEAR_ALERTS = "CLEAR_ALERTS";
